#
title: Duetto
tagline: Augmented crativity
description: One sentence describing what the group works on.

email: denise.lanzieri@sony.com
institution: Sony Computer Science Laboratories – Rome
address_lines:
  - Centro Studi e Ricerche "Enrico Fermi" – CREF
  - Via Panisperna, 89/a
  - 00184 Roma

github: https://github.com/denise-lanzieri-csl
scholar: "#"


url: "https://denise-lanzieri-csl.github.io"
baseurl: "/Duetto"


 
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .jekyll-cache
